# For this, search for "shiny" and run.
# For best results set calcy as: $NameShort$$IV_AVG$, the script takes care of the leading symbols

locations:
  !include config/locations/redminote1080x2400.yaml

waits:
  !include config/waits/redminote1080x2400.yaml

blacklist:
  -
  #disabled because of https://github.com/Azelphur/PokemonGo-CalcyIV-Renamer/issues/47
  #!include config/blacklist.yaml

actions:
  !include config/actions/emi_shiny.yaml
