## locations for a Redmi Note 5
# use a lucky nonevolved poke to calibrate calcy
# and make sure it grabs the moves

rename: [540, 920]
next: [1000, 410]
rename_ok: [550, 1170]
close_calcy_dialog: [930, 1415]
favorite_button: [970, 160]
favorite_button_box: [970, 140, 1000, 180]
pokemon_menu_button: [930, 2020]
appraise_button: [940, 1620]
continue_appraisal: [550, 2020]
calcy_appraisal_save_button: [890, 935]
dismiss_calcy: [540, 1600]
appraisal_box: [70, 1920, 1020, 2090]
