## Locations for Xiaomi Redmi Note 5 1080x2400
# Use a nonevolved non-lucky poke (with three buttons) to calibrate calcy
# Check that it's working properly and it grabs the moves on lucky evolved pokemons

rename: [540, 920]
next: [1000, 500]
rename_ok: [550, 1290]
close_calcy_dialog: [930, 1640]
favorite_button: [970, 185]
favorite_button_box: [960, 175, 980, 195]
pokemon_menu_button: [930, 2240]
appraise_button: [930, 1865]
continue_appraisal: [540, 2260]
calcy_appraisal_save_button: [890, 935]
dismiss_calcy: [540, 2260]
appraisal_box: [70, 2170, 1020, 2340]
